# keybinds
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Set the colors
set -g default-terminal "tmux-256color"
set -as terminal-features ",kitty*:RGB"

# set bar colors
set -g status-style "bg=default"

# mouse
set -g mouse on

# shell
set-option -g default-shell "/bin/zsh"
